# Backend Dockerfile
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY . /app

RUN python -m spacy download en_core_web_sm

CMD ["python", "main.py"]